"""Illustrazioni originali: funzioni e dipendenze, senza numeri non verificati."""
from pathlib import Path
from html import escape
ROOT=Path(__file__).resolve().parents[1];assets=ROOT/'monografie/artemis/assets';assets.mkdir(exist_ok=True)
def chart(file,title,cards,note):
 height=155+len(cards)*120
 body=f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 {height}" role="img" aria-labelledby="t d"><title id="t">{escape(title)}</title><desc id="d">{escape(note)}</desc><defs><marker id="a" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8" fill="#67c7ff"/></marker></defs><rect width="1000" height="{height}" fill="#0c1520"/><g font-family="Arial,sans-serif"><text x="35" y="48" fill="#f3f5f7" font-size="26">{escape(title)}</text>'
 for i,(head,desc) in enumerate(cards):
  y=85+i*120;body+=f'<rect x="35" y="{y}" width="930" height="92" rx="8" fill="#132433" stroke="#496a7f"/><text x="60" y="{y+34}" fill="#f5b941" font-size="23">{escape(head)}</text><text x="60" y="{y+68}" fill="#f3f5f7" font-size="20">{escape(desc)}</text>'
  if i<len(cards)-1:body+=f'<path d="M500 {y+95}V{y+114}" stroke="#67c7ff" stroke-width="3" marker-end="url(#a)"/>'
 body+=f'<text x="35" y="{height-53}" fill="#aab4be" font-size="16">{escape(note)}</text><text x="35" y="{height-20}" fill="#aab4be" font-size="15">Rivoluzione Spaziale · illustrazione originale · CC BY 4.0</text></g></svg>';(assets/file).write_text(body,encoding='utf-8')
charts=[
('architettura.svg','ARTEMIS: LA CATENA DI MISSIONE',[('SLS e Orion: dalla Terra','Lancio e viaggio dell’equipaggio; il lander viene preparato separatamente.'),('Incontro con il lander','Rendezvous, docking e trasferimento delle persone.'),('HLS: superficie e risalita','Discesa, lavoro lunare, partenza e nuovo incontro.'),('Orion: il ritorno terrestre','Rientro atmosferico e recupero della capsula.')],'Funzioni qualitative; orbita e sequenza dipendono dalla missione.'),
('sls-funzioni.svg','SLS: ELEMENTI DELLA CONFIGURAZIONE INIZIALE',[('Orion e sistema di fuga','Equipaggio e apparati di sicurezza.'),('Stadio superiore','Spinta necessaria alla fase successiva del viaggio.'),('Stadio centrale','Serbatoi e quattro RS-25 a propellenti liquidi.'),('Due booster solidi','Spinta nella prima parte della salita.')],'Ordine funzionale dall’alto; non è un disegno in scala.'),
('orion-funzioni.svg','ORION: CAPSULA E MODULO DI SERVIZIO',[('Modulo abitato','Persone, guida, protezione e rientro.'),('Modulo europeo di servizio','Propulsione, energia, risorse e gestione termica.'),('Separazione prima del rientro','La capsula prosegue nell’atmosfera, il modulo non viene recuperato.')],'Schema didattico; apparati e connessioni non sono rappresentati integralmente.'),
('scudo.svg','SCUDO ORION: DAL RISULTATO ALLA DECISIONE',[('Artemis I torna','Il veicolo viene conservato per l’analisi.'),('Si osserva perdita di materiale','Il ritorno riuscito non elimina l’anomalia.'),('Indagine e prove','Confronto di dati, campioni e modelli.'),('Decisione per Artemis II','Uso dello scudo disponibile con traiettoria modificata.')],'Sequenza storica; non è una certificazione autonoma redazionale.'),
('aii-viaggio.svg','ARTEMIS II: LA SEQUENZA DEL VIAGGIO',[('1 aprile 2026','Partenza da Kennedy e prime verifiche.'),('Verso la Luna','Spinta, navigazione, vita a bordo e comunicazioni.'),('6 aprile 2026','Sorvolo; nessun inserimento di un lander sulla superficie.'),('10 aprile 2026','Rientro nell’atmosfera terrestre e ammaraggio.')],'Cronologia qualitativa; non rappresenta distanze o tempi in scala.'),
('piani.svg','LE MISSIONI: PIANO STORICO E REVISIONE 2026',[('Artemis I · risultato','Prova senza equipaggio conclusa nel dicembre 2022.'),('Artemis II · risultato','Volo umano attorno alla Luna concluso nell’aprile 2026.'),('Artemis III · obiettivo 2027','Prova integrata in orbita terrestre, non allunaggio.'),('Artemis IV · obiettivo 2028','Missione di allunaggio, subordinata alle capacità richieste.')],'La numerazione non garantisce automaticamente la data o il completamento.'),
('hls-confronto.svg','DUE STRADE PER IL LANDER',[('SpaceX · Starship HLS','Variante lunare di una famiglia di veicoli molto grande.'),('Blue Origin · Blue Moon Mark 2','Lander umano distinto dal dimostratore cargo Mark 1.'),('Requisiti comuni','Incontro, persone, superficie e risalita; campagne preparatorie proprie.')],'Confronto di funzioni; non assegna un vincitore né confronta prezzi per volo.'),
('rifornimento.svg','IL RIFORNIMENTO È UNA CAMPAGNA',[('Portare le risorse','Lanci e traiettorie compatibili con la nave ricevente.'),('Connettere e trasferire','Rendezvous, tenuta, gestione dei fluidi.'),('Conservare e misurare','Temperatura, pressione, evaporazione e riserve.'),('Partire per la missione','Accettazione delle condizioni prima della manovra.')],'Non presume un numero fisso di cisterne o una dimostrazione già conclusa.'),
('base.svg','UNA BASE NON È SOLO UN HABITAT',[('Preparazione','Conoscere il sito e consegnare strumenti.'),('Infrastrutture iniziali','Energia, comunicazioni, mobilità e logistica.'),('Operazioni ricorrenti','Equipaggi, manutenzione e rifornimenti.'),('Presenza prolungata','Risorse e sistemi con margini per guasti e ritardi.')],'Dipendenze funzionali: nessuna data di completamento viene garantita.'),
('campioni.svg','IL CAMPIONE SCIENTIFICO: UN’INTERA CATENA',[('Scegliere e descrivere','Geologia, contesto e documentazione del sito.'),('Raccogliere e proteggere','Strumenti, contenitori e contaminazione.'),('Trasportare sulla Terra','Massa disponibile e catena delle responsabilità.'),('Analizzare e conservare','Laboratori e accesso scientifico nel tempo.')],'Schema originale: valore scientifico e massa del campione non coincidono.'),
('rischi.svg','COME SI LEGGE UN RISCHIO DI CALENDARIO',[('Capacità necessaria','Quale funzione della missione dipende dal componente?'),('Prova disponibile','Quale test l’ha verificata e in quali condizioni?'),('Margine e alternativa','Che cosa accade se il componente ritarda o non funziona?'),('Decisione aggiornata','Data, responsabilità e criterio di accettazione.')],'Analisi editoriale, non previsione probabilistica del lancio.')]
for item in charts:chart(*item)
print(len(charts),'schemi originali')
